# Generated by Django 4.1.2 on 2022-10-12 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bike', '0002_bike_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bike', to='bike.type'),
        ),
        migrations.AlterField(
            model_name='evaluate',
            name='bike',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bike', to='bike.bike'),
        ),
        migrations.AlterField(
            model_name='evaluate',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bike', to=settings.AUTH_USER_MODEL),
        ),
    ]
