# Generated by Django 4.1.2 on 2022-10-12 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bike', '0003_alter_bike_type_alter_evaluate_bike_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.IntegerField(blank=True)),
            ],
            options={
                'db_table': 'rent_type',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('rent_day_start', models.DateTimeField()),
                ('rent_day_end', models.DateTimeField()),
                ('price', models.IntegerField(blank=True)),
                ('status', models.BooleanField(default=False)),
                ('bike_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bike.bike')),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('type_rent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.renttype')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
