# Generated by Django 4.1.2 on 2022-10-13 08:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(default='', max_length=255)),
                ('slug', models.SlugField()),
                ('content', models.TextField(default='')),
                ('post_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'posts',
            },
        ),
    ]
